#Description :
#In this file : list of all parameters used in kernel. Don't update it!

#Exemple : 
#key:value

#Datas
#**************************************************************************************

#Path
PARAM_KERNEL_PATH_COMP_KRN_HANDLE:global/config/LoadingKernelHandle.yml
PARAM_KERNEL_PATH_COMP_CONF_BASIC:global/config/LoadingBasic.yml
PARAM_KERNEL_PATH_COMP_CONF_STD:global/config/LoadingStandard.yml
PARAM_KERNEL_PATH_ROUTING:global/config/Routing.yml
PARAM_KERNEL_PATH_PARAM_EXTEND_BASIC:global/config/ParamExtendBasic.yml
PARAM_KERNEL_PATH_PARAM_EXTEND_STD:global/config/ParamExtendStandard.yml
PARAM_KERNEL_PATH_SERVICE:global/config/Service.yml



#Component loading
PARAM_KERNEL_COMP_CONF_NM:component_nm_
PARAM_KERNEL_COMP_CONF_PATH:component_path
PARAM_KERNEL_COMP_CONF_INC:component_route_include
PARAM_KERNEL_COMP_CONF_EXC:component_route_exclude

PARAM_KERNEL_COMP_VAR_RTE_SEPARATOR::
PARAM_KERNEL_COMP_VAR_RTE_ALL:*



#Route
PARAM_KERNEL_ROUTE_TAG_ARG:route
PARAM_KERNEL_ROUTE_TAG_NM:NM
PARAM_KERNEL_ROUTE_TAG_URL:URL
PARAM_KERNEL_ROUTE_TAG_PATH:PATH

PARAM_KERNEL_ROUTE_CONF_NM:route_nm_
PARAM_KERNEL_ROUTE_CONF_URL:route_url
PARAM_KERNEL_ROUTE_CONF_PATH:route_path
PARAM_KERNEL_ROUTE_CONF_DEFAULT:route_default

PARAM_KERNEL_ROUTE_VAR_START:{
PARAM_KERNEL_ROUTE_VAR_END:}

PARAM_KERNEL_ROUTE_SEPARATOR::

PARAM_KERNEL_ROUTE_ERR_PATH:ERR_PATH
PARAM_KERNEL_ROUTE_ERR_ACTION:ERR_ACTION



#Service
PARAM_KERNEL_SVC_CONF_NM:service_nm_
PARAM_KERNEL_SVC_CONF_PATH:service_class_path
PARAM_KERNEL_SVC_CONF_ARG:service_class_args

PARAM_KERNEL_SVC_TAG_NM:NM
PARAM_KERNEL_SVC_TAG_PATH:PATH
PARAM_KERNEL_SVC_TAG_ARG:ARG

PARAM_KERNEL_SVC_ARG_SVC_ID_START:[
PARAM_KERNEL_SVC_ARG_SVC_ID_END:]

PARAM_KERNEL_SVC_ARG_CONST_START:{
PARAM_KERNEL_SVC_ARG_CONST_END:}

PARAM_KERNEL_SVC_ARG_VAL_START:"
PARAM_KERNEL_SVC_ARG_VAL_END:"

PARAM_KERNEL_SVC_ARG_SEPARATOR:,



#Session
PARAM_KERNEL_SES_SAVE_TAG:session_save



#Save
PARAM_KERNEL_SAVE_TAG_TAB:save_table
PARAM_KERNEL_SAVE_TAG_COOK_TAB:save_cook_table
PARAM_KERNEL_SAVE_TIMER_COOK_TAB:63072000



#View engine
PARAM_KERNEL_VIEW_ENG_ESCAPE:\
PARAM_KERNEL_VIEW_ENG_EXTEND_START:[[Extend src="
PARAM_KERNEL_VIEW_ENG_EXTEND_END:"/]]
PARAM_KERNEL_VIEW_ENG_BLOCK_START_START:[[Block:
PARAM_KERNEL_VIEW_ENG_BLOCK_START_END:]]
PARAM_KERNEL_VIEW_ENG_BLOCK_END_START:[[/Block:
PARAM_KERNEL_VIEW_ENG_BLOCK_END_END:]]
PARAM_KERNEL_VIEW_ENG_VALUE_HIDE_START_START:[[Hidden:
PARAM_KERNEL_VIEW_ENG_VALUE_HIDE_START_END:]]
PARAM_KERNEL_VIEW_ENG_VALUE_HIDE_END_START:[[/Hidden:
PARAM_KERNEL_VIEW_ENG_VALUE_HIDE_END_END:]]


