#Description :
#In this file : only path to extend param : extend class ParamExtend

#Exemple : 
#Key = a key
#Val = path of the class extend class ParamExtend

#Datas
#**************************************************************************************

PARAM_EXTEND_GLOB:global/src/config/ParamGlob.php