#Description :
#In this file : only path to extend param standard : extend class ParamExtend

#Exemple : 
#Key = a key
#Val = path of the class extend class ParamExtend

#Datas
#**************************************************************************************